# Generated by Django 2.2.12 on 2020-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_auto_20200506_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
